### ISSUE TITLE
Please GPL your app (it is currently released under the GFDL only, which is not a good choice)

### ISSUE THREAD

**Issue by unforgettableid** [kshark27/UltraExplorer#2]
Dear kshark27,

Your [license file](https://github.com/kshark27/UltraExplorer/blob/master/License.md) includes nothing but a copy of the GNU Free Documentation License.

This license was not designed to be a source-code license.  It was designed for use only for documentation.  That is why it is called the GNU Free **Documentation** license.  It is not a good choice.

You should instead use a different license.  The [GPL version 3](https://gist.githubusercontent.com/jnrbsn/708961/raw/16d89e0a34c0bc274e1939e28a3f98ee2b380858/GPL.md) is a fine choice.

Does this make sense?

P.S.  Thank you very much for writing Ultra Explorer and posting it to GitHub.

**Comment by kartikhimself** [comment]
Thanks for the information. I made the required changes. :)

**Comment by unforgettableid** [comment]
Well, you started making the required changes.  Thank you for that.  :)

You copied and pasted a [poorly-formatted version](http://www.gnu.org/licenses/gpl.txt) of the GPL version 3 into your [Readme file](https://github.com/kshark27/UltraExplorer/blob/master/README.md).

But the Readme file is not really the right place to include the entire text of the license.  I wonder if you might please do the following?
1.  To remove the license text from your Readme file
2.  To copy and paste a [better-formatted version](https://gist.githubusercontent.com/jnrbsn/708961/raw/16d89e0a34c0bc274e1939e28a3f98ee2b380858/GPL.md) of the GPLv3 into your [License.md file](https://github.com/kshark27/UltraExplorer/blob/master/License.md)

**Comment by unforgettableid** [comment]
I see this is done.  Thank you very much!
